server:
  port: 8090
  servlet:
    context-path: /question
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/text?useUnicode=true&autoReconnect=true&useSSL=false&requireSSL=false&failOverReadOnly=false&testOnBorrow=true&serverTimezone=Asia/Shanghai&validationQuery=select 1
    username: root
    password: 46320974
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-init-sql: set names utf8mb4
  profiles:
    active: local


#mybatis配置
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    call-setters-on-nulls: true
  mapper-locations: classpath:edu/hope/biz/mapper/xml/*.xml

#是否开启swagger
mconfig:
  swagger-ui-open: true
